---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hungpod-cm
  labels:
    {{- include "..labels" . | nindent 4 }}
data:
{{- $scope := . }}
{{- range $path, $_ :=  .Files.Glob  "scripts/*" }}
{{- with $scope}}
  {{ base $path }}: |
{{ .Files.Get $path | indent 4 }}
{{- end }}
{{ end }}