{{- if .Values.createRBAC -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "..serviceAccountName" . }}-role
rules:
  - verbs:
      - get
      - watch
      - list
      - delete
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - pods/exec
{{- end }}
