{{- if .Values.createRBAC -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "..serviceAccountName" . }}-rb
subjects:
  - kind: ServiceAccount
    name: {{ include "..serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "..serviceAccountName" . }}-role
{{- end }}
